# supabase/config.toml

[functions.process-example-queue]
  enabled = true
  verify_jwt = true
  import_map = "./functions/process-example-queue/deno.json"
  entrypoint = "./functions/process-example-queue/index.ts"

[functions.save-push-subscription]
  # 이 함수는 클라이언트에서 직접 호출되므로 별도 스케줄 없음

[functions.send-daily-reminder]
  # 스케줄은 pg_cron을 통해 관리됩니다.